# Generated by Django 5.2.17 on 2026-09-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_invitation_membershipnotice_user_email_last_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='signup_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='signup_token_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
