# Generated by Django 5.2.17 on 2026-09-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_invitation_signup_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateField()),
                ('amount_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', editable=False, max_length=3)),
                ('classification', models.CharField(choices=[('expense', 'Expense'), ('refund', 'Refund'), ('income', 'Income'), ('transfer', 'Transfer or card payment')], default='expense', max_length=10)),
                ('pending', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.account')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'posted_on', 'id'], name='budget_tran_account_23dfdf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='transaction_amount_positive'), models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='transaction_usd_only')],
            },
        ),
    ]
