# Generated by Django 5.2.17 on 2026-09-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('classification', models.CharField(blank=True, choices=[('expense', 'Expense'), ('refund', 'Refund'), ('income', 'Income'), ('transfer', 'Transfer or card payment')], max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='budget.transaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='budget.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transaction', 'workspace'), name='annotation_one_per_workspace')],
            },
        ),
    ]
