# Generated by Django 5.2.17 on 2026-09-25 19:46

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


STANDARD = ["Groceries", "Dining", "Housing", "Utilities", "Transport", "Shopping", "Health", "Entertainment", "Subscriptions", "Travel"]


def seed(apps, schema_editor):
    Category, Workspace = apps.get_model("budget", "Category"), apps.get_model("budget", "Workspace")
    Category.objects.bulk_create(Category(workspace=w, name=n) for w in Workspace.objects.all() for n in STANDARD)


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_transactionannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('archived', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='transactionannotation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='budget.category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='category_name_unique_per_workspace'),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
