# Generated by Django 5.2.17 on 2026-09-25 19:54

import django.db.models.deletion
from django.db import migrations, models


def mark_manual(apps, schema_editor):
    # Categories set before rules existed were all chosen by hand.
    apps.get_model("budget", "TransactionAnnotation").objects.exclude(category=None).update(category_source="manual")


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionannotation',
            name='category_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('rule', 'Rule')], max_length=6),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contains', 'Name contains'), ('exact', 'Name is exactly')], default='contains', max_length=8)),
                ('pattern', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='budget.category')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='budget.workspace')),
            ],
        ),
        migrations.RunPython(mark_manual, migrations.RunPython.noop),
    ]
