# Generated by Django 5.2.17 on 2026-09-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_match', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=5)),
                ('limit_cents', models.BigIntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budget.category')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budget.workspace')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('limit_cents__gt', 0)), name='budget_limit_positive'), models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('name_match', '')), models.Q(('category__isnull', True), models.Q(('name_match', ''), _negated=True)), _connector='OR'), name='budget_one_target')],
            },
        ),
    ]
