# Generated by Django 5.2.17 on 2026-09-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_budgetalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='kind',
            field=models.CharField(choices=[('flexible', 'Flexible spending'), ('fixed', 'Fixed bill'), ('irregular', 'Yearly or irregular cost')], default='flexible', max_length=9),
        ),
        migrations.AddField(
            model_name='workspace',
            name='expected_income_cents',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
