# Generated by Django 5.2.17 on 2026-09-25 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_budget_kinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.BigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='split_lines', to='budget.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_lines', to='budget.transaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_lines', to='budget.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'transaction'], name='budget_spli_workspa_b79403_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='split_line_amount_positive')],
            },
        ),
    ]
