# Generated by Django 5.2.17 on 2026-09-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_splitline'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='split_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_rules', to='budget.category'),
        ),
        migrations.AddField(
            model_name='rule',
            name='split_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='splitline',
            name='from_rule',
            field=models.BooleanField(default=False),
        ),
    ]
