# Generated by Django 5.2.17 on 2026-09-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_row',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('done', 'Imported')], default='preview', max_length=7)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='budget.account')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='import_batch',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.importbatch'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('import_batch', 'source_row'), name='transaction_source_row_once'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'done')), fields=('account', 'sha256'), name='import_file_once'),
        ),
    ]
