# Generated by Django 5.2.17 on 2026-09-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_csv_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
