# Generated by Django 5.2.17 on 2026-09-28 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_email_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True)),
                ('access_token', models.TextField()),
                ('institution_name', models.CharField(blank=True, max_length=100)),
                ('cursor', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=5)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('history_ready', models.BooleanField(default=False)),
                ('sync_started_at', models.DateTimeField(null=True)),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='mask',
            field=models.CharField(blank=True, editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='account',
            name='provider_account_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_category',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('account', 'provider_id'), name='transaction_provider_id_once'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='connection',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='budget.bankconnection'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('connection__isnull', False)), fields=('connection', 'provider_account_id'), name='account_imported_once'),
        ),
    ]
