# Generated by Django 5.2.17 on 2026-09-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_plaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankconnection',
            name='institution_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='needs_sync',
            field=models.BooleanField(default=False),
        ),
    ]
