# Generated by Django 5.2.17 on 2026-09-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_plaid_webhooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_cents',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='balance_kind',
            field=models.CharField(blank=True, choices=[('', 'Not counted'), ('asset', 'Something you own'), ('liability', 'Something you owe')], max_length=9),
        ),
        migrations.AddField(
            model_name='account',
            name='balance_updated_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
