# Generated by Django 5.2.17 on 2026-09-28 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_net_worth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('bill', 'Bill'), ('income', 'Income')], default='bill', max_length=6)),
                ('amount_cents', models.BigIntegerField()),
                ('interval', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=7)),
                ('anchor_on', models.DateField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='confirmed', max_length=9)),
                ('remind', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring', to='budget.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BillReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_reminders', to=settings.AUTH_USER_MODEL)),
                ('recurring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='budget.recurring')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recurring',
            constraint=models.UniqueConstraint(fields=('workspace', 'pattern'), name='recurring_once'),
        ),
        migrations.AddConstraint(
            model_name='recurring',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='recurring_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='billreminder',
            constraint=models.UniqueConstraint(fields=('recurring', 'recipient', 'due_on'), name='bill_reminder_once'),
        ),
    ]
