# Generated by Django 5.2.17 on 2026-09-28 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goals_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('savings', 'Save up'), ('debt', 'Pay off a debt')], default='savings', max_length=7)),
                ('target_cents', models.BigIntegerField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('manual_cents', models.BigIntegerField(default=0)),
                ('start_cents', models.BigIntegerField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='budget.account')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='budget.workspace')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('target_cents__gt', 0)), name='goal_target_positive'), models.CheckConstraint(condition=models.Q(('manual_cents__gte', 0)), name='goal_manual_not_negative')],
            },
        ),
    ]
