# Generated by Django 5.2.17 on 2026-09-28 17:08

from django.db import migrations, models
from django.db.models import Q


def backfill(apps, schema_editor):
    """Older rows kept only a positive amount. Income and refunds came in; a transfer came in when the bank said so,
    when it was a CSV row (CSV money out always imported as an expense), or when it was a payment onto a card or loan."""
    Transaction = apps.get_model("budget", "Transaction")
    Transaction.objects.filter(
        Q(classification__in=["income", "refund"])
        | Q(classification="transfer") & (Q(provider_category__startswith="TRANSFER_IN") | Q(import_batch__isnull=False)
                                          | Q(provider_category__startswith="LOAN_PAYMENTS", account__balance_kind="liability"))
    ).update(money_in=True)


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='money_in',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
