# Generated by Django 5.2.17 on 2026-09-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_money_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_savings',
            field=models.BooleanField(null=True),
        ),
    ]
