# Generated by Django 5.2.17 on 2026-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_account_is_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='kind',
            field=models.CharField(choices=[('contains', 'Name contains'), ('exact', 'Name is exactly'), ('words', 'Name has all of')], default='contains', max_length=8),
        ),
    ]
