from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import RedirectView

from budget import views
from budget import invitation_views
from budget.forms import VerifiedPasswordResetForm

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("password-reset/", auth_views.PasswordResetView.as_view(form_class=VerifiedPasswordResetForm), name="password_reset"),
    path("password-reset/sent/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("more/", RedirectView.as_view(pattern_name="settings")),
    path("settings/", views.settings_page, name="settings"),
    path("alerts/", views.alerts, name="alerts"),
    path("settings/username/", views.username_change, name="username_change"),
    path("settings/email/", views.email_change, name="email_change"),
    path("settings/email/<str:token>/", views.email_change_confirm, name="email_change_confirm"),
    path("settings/password/", views.PasswordChange.as_view(), name="password_change"),
    path("email/verify/", invitation_views.email_verify, name="email_verify"),
    path("email/verify/<str:token>/", invitation_views.email_verify, name="email_verify_confirm"),
    path("invitations/<str:token>/", invitation_views.invitation_accept, name="invitation_accept"),
    path("invitations/<str:token>/register/", invitation_views.invitation_register, name="invitation_register"),
    path("invitations/<str:token>/register/<str:proof>/", invitation_views.invitation_register, name="invitation_register_confirm"),
    path("workspaces/<int:workspace_id>/invitations/", invitation_views.invitation_create, name="invitation_create"),
    path("workspaces/<int:workspace_id>/invitations/<int:invitation_id>/revoke/", invitation_views.invitation_revoke, name="invitation_revoke"),
    path("health/", views.health),
    path("ready/", views.ready),
    path("robots.txt", views.robots),
    path("accounts/new/", views.account_create, name="account_create"),
    path("groups/new/", views.group_create, name="group_create"),
    path("workspaces/<int:workspace_id>/", views.workspace_detail, name="workspace"),
    path("workspaces/<int:workspace_id>/transactions/", views.transaction_list, name="transactions"),
    path("workspaces/<int:workspace_id>/transactions/export.csv", views.transaction_export, name="transaction_export"),
    path("workspaces/<int:workspace_id>/accounts/<int:account_id>/", views.account_detail, name="account_detail"),
    path("workspaces/<int:workspace_id>/accounts/<int:account_id>/transactions/new/", views.transaction_edit, name="transaction_create"),
    path("workspaces/<int:workspace_id>/accounts/<int:account_id>/transactions/<int:transaction_id>/", views.transaction_edit, name="transaction_edit"),
    path("workspaces/<int:workspace_id>/accounts/<int:account_id>/transactions/<int:transaction_id>/annotate/", views.annotation_edit, name="annotation_edit"),
    path("workspaces/<int:workspace_id>/categories/", views.category_list, name="categories"),
    path("workspaces/<int:workspace_id>/categories/<int:category_id>/", views.category_edit, name="category_edit"),
    path("workspaces/<int:workspace_id>/categories/<int:category_id>/add/", views.category_add, name="category_add"),
    path("workspaces/<int:workspace_id>/budgets/", views.budget_list, name="budgets"),
    path("workspaces/<int:workspace_id>/budgets/new/", views.budget_edit, name="budget_create"),
    path("workspaces/<int:workspace_id>/budgets/<int:budget_id>/", views.budget_edit, name="budget_edit"),
    path("workspaces/<int:workspace_id>/budgets/<int:budget_id>/delete/", views.budget_delete, name="budget_delete"),
    path("workspaces/<int:workspace_id>/rules/", views.rule_list, name="rules"),
    path("workspaces/<int:workspace_id>/rules/new/", views.rule_edit, name="rule_create"),
    path("workspaces/<int:workspace_id>/rules/<int:rule_id>/", views.rule_edit, name="rule_edit"),
    path("workspaces/<int:workspace_id>/sharing/", views.sharing, name="sharing"),
    path("workspaces/<int:workspace_id>/members/<int:member_id>/remove/", views.member_remove, name="member_remove"),
]
